# Generated by Django 6.0.6 on 2026-06-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='Company Name')),
                ('industry', models.CharField(choices=[('tech', 'Ta9nia'), ('construction', 'Maqawalat'), ('medical', 'Tebi'), ('education', 'Ta3lemi'), ('marketing', 'Tasweq'), ('finance', 'Mali'), ('other', 'Okhra')], max_length=50, verbose_name='Industry')),
                ('employee_count', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employees Count')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Founded Year')),
                ('headquarters', models.CharField(max_length=200, verbose_name='Headquarters')),
                ('about', models.TextField(verbose_name='About')),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('commercial_registration', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Commercial Registration')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
