# Generated by Django 6.0.6 on 2026-06-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('internship', 'Internship')], max_length=20, verbose_name='Job Type')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Salary')),
                ('is_salary_negotiable', models.BooleanField(default=False, verbose_name='Salary Negotiable')),
                ('required_skills', models.TextField(verbose_name='Required Skills')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('deadline', models.DateField(verbose_name='Application Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_filled', models.BooleanField(default=False, verbose_name='Filled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20, verbose_name='Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed')),
                ('employer_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='graduates.graduate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'unique_together': {('job', 'graduate')},
            },
        ),
    ]
