# Generated by Django 6.0.6 on 2026-06-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(max_length=20, unique=True, verbose_name='University ID')),
                ('graduation_year', models.IntegerField(verbose_name='Graduation Year')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA')),
                ('major', models.CharField(max_length=100, verbose_name='Major')),
                ('minor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Minor')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('current_job_status', models.CharField(choices=[('working', 'Working'), ('seeking', 'Seeking Job'), ('studying', 'Postgraduate'), ('intern', 'Intern'), ('entrepreneur', 'Entrepreneur')], default='seeking', max_length=20, verbose_name='Job Status')),
                ('current_job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Job Title')),
                ('current_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Company')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Picture')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('profile_views', models.IntegerField(default=0, verbose_name='Profile Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
