# Generated by Django 6.0.6 on 2026-06-04 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='reward_points',
            field=models.IntegerField(default=0, verbose_name='نقاط الحوافز'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='نبذة تعريفية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الشركة الحالية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='current_job_status',
            field=models.CharField(choices=[('working', 'يعمل'), ('seeking', 'يبحث عن عمل'), ('studying', 'طالب دراسات عليا'), ('intern', 'متدرب'), ('entrepreneur', 'رائد أعمال')], default='seeking', max_length=20, verbose_name='الحالة الوظيفية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي الحالي'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='المعدل التراكمي'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='graduation_year',
            field=models.IntegerField(verbose_name='سنة التخرج'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='حساب موثق'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='major',
            field=models.CharField(max_length=100, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='minor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص الفرعي'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='profile_views',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='university_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='الرقم الجامعي'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.CreateModel(
            name='AcademicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='رابط المشروع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='صورة المشروع')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_projects', to='graduates.graduate')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشهادة')),
                ('issuing_organization', models.CharField(max_length=100, verbose_name='جهة الإصدار')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='رابط الشهادة')),
                ('credential_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='ملف الشهادة')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='graduates.graduate')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الزائر')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاهدة')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_log', to='graduates.graduate')),
                ('viewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المهارة')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='graduates.graduate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('company', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='هل ما زلت تعمل هنا؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المهام')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='graduates.graduate')),
            ],
        ),
    ]
