# Generated by Django 6.0.6 on 2026-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_remove_academicproject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
    ]
