# Generated by Django 6.0.6 on 2026-07-05 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date', models.DateTimeField(verbose_name='التاريخ')),
                ('location', models.CharField(max_length=200, verbose_name='المكان')),
                ('is_upcoming', models.BooleanField(default=True, verbose_name='قادم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='صورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فعالية',
                'verbose_name_plural': 'الفعاليات',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_name', models.CharField(max_length=100, verbose_name='اسم الخريج')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='القصة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories/', verbose_name='صورة')),
                ('graduation_year', models.IntegerField(verbose_name='سنة التخرج')),
                ('current_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة الحالية')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'قصة نجاح',
                'verbose_name_plural': 'قصص النجاح',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='جامعة إقليم سبأ', max_length=200, verbose_name='اسم الجامعة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university/', verbose_name='شعار الجامعة')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
            ],
            options={
                'verbose_name': 'معلومات الجامعة',
                'verbose_name_plural': 'معلومات الجامعة',
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('category', models.CharField(choices=[('pdf', 'ملف PDF'), ('video', 'فيديو'), ('doc', 'مستند'), ('link', 'رابط خارجي')], default='pdf', max_length=20, verbose_name='النوع')),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/', verbose_name='الملف')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط خارجي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'ordering': ['-created_at'],
            },
        ),
    ]
