# Generated by Django 6.0.6 on 2026-07-05 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('date', models.DateTimeField(verbose_name='التاريخ')),
                ('location', models.CharField(max_length=200, verbose_name='المكان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_name', models.CharField(max_length=100, verbose_name='اسم الخريج')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='القصة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='صورة')),
                ('graduation_year', models.IntegerField(verbose_name='سنة التخرج')),
                ('current_job', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة الحالية')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('category', models.CharField(choices=[('pdf', 'PDF'), ('video', 'فيديو'), ('doc', 'مستند'), ('link', 'رابط خارجي')], default='pdf', max_length=20, verbose_name='النوع')),
                ('file', models.FileField(blank=True, null=True, upload_to='study/', verbose_name='الملف')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
