# Generated by Django 6.0.6 on 2026-07-05 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='إجازة رسمية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حدث تقويمي',
                'verbose_name_plural': 'التقويم الأكاديمي',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدورة')),
                ('instructor', models.CharField(blank=True, max_length=200, verbose_name='المدرب')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='المستوى')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='المدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='صورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوظيفة')),
                ('company', models.CharField(max_length=200, verbose_name='الشركة')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('requirements', models.TextField(blank=True, verbose_name='المتطلبات')),
                ('job_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('remote', 'عن بعد'), ('internship', 'تدريب')], default='full_time', max_length=20, verbose_name='نوع الوظيفة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='الراتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='آخر موعد للتقديم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'وظيفة',
                'verbose_name_plural': 'الوظائف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشريك')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='الشعار')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('announcement', '📢 إعلان'), ('event', '📅 فعالية'), ('achievement', '🏆 إنجاز'), ('general', '📰 خبر عام'), ('job', '💼 وظيفة')], default='general', max_length=20, verbose_name='التصنيف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='university/news/', verbose_name='صورة')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط خارجي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خبر/إعلان',
                'verbose_name_plural': 'الأخبار والإعلانات',
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='SuccessStory',
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-created_at'], 'verbose_name': 'مادة دراسية', 'verbose_name_plural': 'المواد الدراسية'},
        ),
    ]
